module.exports = {
	frame: 0,
	data : null,
	packetNum: 0,
	score: 0,
	canvas : null,
	bg : null,
	player : null,
	screenHeight: null,
	screenWidth: null,
	bullets: [],
	enemys: [],
	enemyId : 0,
	shootType: 1,
	shootDirection : 1,
	enemyScore : 0,
	overWindow: null,
	isOver : false,
	value: 0,
	maxEnemyNum: 0,
	speed: 1,
	rankList: [],
	rankLayout: null,
}; 