module.exports = {
	debug : false,
	frame: 0,
	userid:-1,
	userinfo: [],
	gameinfo: [],
	isPlayer: false,
	roomID: -1,
	ruleWindow: null,
	create_page: null,
	me_page: null,
	index_page: null,
	indexButton: null,
	screenHeight: null,
	screenWidth: null,
	url: 'https://game.cj102.com',
	redPackNum: 0,
	money: 0,
	level: 'level1',
	orderid: '-1',
	realOrderId: '',
	wxCommon: null,
	createrRoomId: null,
	step: '',
	isWxMini: false,
	session: null,
	initRoomID: '0',
	shouldLeaveRoom: false
}; 